-- =====================================================================
-- 01_MYEDW_SCHEMA - CHUNK 1: CORE SETUP AND REFERENCE TABLES
-- Target: PostgreSQL 16.x
-- Schema: myedw
-- Author: Generated for Isar (MyPersonalSpace Project)
-- =====================================================================

DROP SCHEMA IF EXISTS myedw CASCADE;
CREATE SCHEMA myedw AUTHORIZATION postgres;
SET search_path TO myedw, public;

-- Enable UUIDs
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- =====================================================================
-- Reference: Countries
-- =====================================================================
CREATE TABLE myedw.reference_countries (
    country_code CHAR(2) PRIMARY KEY,
    country_name TEXT NOT NULL,
    region TEXT,
    iso3 CHAR(3),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE myedw.reference_countries IS 'List of countries with ISO codes.';
COMMENT ON COLUMN myedw.reference_countries.country_code IS '2-letter ISO country code.';
COMMENT ON COLUMN myedw.reference_countries.iso3 IS '3-letter ISO code.';
COMMENT ON COLUMN myedw.reference_countries.region IS 'Geographic region grouping.';

-- =====================================================================
-- Reference: Currencies
-- =====================================================================
CREATE TABLE myedw.reference_currencies (
    currency_code CHAR(3) PRIMARY KEY,
    currency_name TEXT NOT NULL,
    symbol TEXT,
    minor_units INT DEFAULT 2,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE myedw.reference_currencies IS 'List of currencies used in the system.';

-- =====================================================================
-- Reference: Departments
-- =====================================================================
CREATE TABLE myedw.reference_departments (
    department_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_name TEXT NOT NULL UNIQUE,
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE myedw.reference_departments IS 'Corporate departments such as HR, Finance, Support, etc.';

-- =====================================================================
-- Reference: Job Titles
-- =====================================================================
CREATE TABLE myedw.reference_job_titles (
    job_title_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title_name TEXT NOT NULL UNIQUE,
    department_id BIGINT REFERENCES myedw.reference_departments(department_id) ON DELETE SET NULL,
    description TEXT
);
COMMENT ON TABLE myedw.reference_job_titles IS 'Catalog of all HR job titles and mappings to departments.';

-- =====================================================================
-- Reference: Sales Channels
-- =====================================================================
CREATE TABLE myedw.reference_sales_channels (
    channel_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_name TEXT NOT NULL UNIQUE,
    description TEXT
);
COMMENT ON TABLE myedw.reference_sales_channels IS 'Available sales and marketing channels such as Online, Retail, Partner.';

-- =====================================================================
-- Reference: Payment Methods
-- =====================================================================
CREATE TABLE myedw.reference_payment_methods (
    payment_method_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    method_name TEXT NOT NULL UNIQUE,
    description TEXT
);
COMMENT ON TABLE myedw.reference_payment_methods IS 'Payment methods accepted by the business (e.g., Credit Card, PayPal, Wire).';

-- =====================================================================
-- Reference: Calendar
-- =====================================================================
CREATE TABLE myedw.reference_calendar (
    date_id DATE PRIMARY KEY,
    year INT,
    quarter INT,
    month INT,
    day INT,
    week INT,
    is_weekend BOOLEAN,
    is_holiday BOOLEAN DEFAULT FALSE
);
COMMENT ON TABLE myedw.reference_calendar IS 'Standardized business calendar with date-based attributes.';

-- =====================================================================
-- Reference: Document Types
-- =====================================================================
CREATE TABLE myedw.reference_document_types (
    doc_type TEXT PRIMARY KEY,
    description TEXT
);
COMMENT ON TABLE myedw.reference_document_types IS 'Supported document types for repository management.';

-- =====================================================================
-- Reference: Countries and Currencies Relationship
-- =====================================================================
ALTER TABLE myedw.reference_countries
ADD COLUMN currency_code CHAR(3) REFERENCES myedw.reference_currencies(currency_code);

-- =====================================================================
-- Reference: Employee Status
-- =====================================================================
CREATE TABLE myedw.reference_employee_status (
    status_code TEXT PRIMARY KEY,
    description TEXT
);
COMMENT ON TABLE myedw.reference_employee_status IS 'Employee status values like Active, Terminated, On Leave.';

-- ===============================================================
-- Reference Support Ticket
-- ===============================================================
CREATE TABLE IF NOT EXISTS myedw.reference_support_ticket_status (
    status_code TEXT PRIMARY KEY,
    status_label TEXT NOT NULL
);

COMMENT ON TABLE myedw.reference_support_ticket_status IS 'Standardized lifecycle statuses for customer support tickets.';

