-- =====================================================================
-- 01_MYEDW_SCHEMA - CHUNK 2: CUSTOMER + SALES DOMAIN
-- Target: PostgreSQL 16.x
-- Schema: myedw
-- =====================================================================

SET search_path TO myedw, public;

-- =====================================================================
-- Customer Profiles
-- =====================================================================
CREATE TABLE myedw.customer_profiles (
    customer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_code TEXT UNIQUE NOT NULL,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    email TEXT UNIQUE,
    phone TEXT,
    created_date DATE DEFAULT CURRENT_DATE,
    country_code CHAR(2) REFERENCES myedw.reference_countries(country_code),
    loyalty_points BIGINT DEFAULT 0
);
COMMENT ON TABLE myedw.customer_profiles IS 'Master record for each customer in the system.';
COMMENT ON COLUMN myedw.customer_profiles.customer_code IS 'Externally visible unique customer code.';

-- =====================================================================
-- Customer Accounts
-- =====================================================================
CREATE TABLE myedw.customer_accounts (
    account_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL REFERENCES myedw.customer_profiles(customer_id) ON DELETE CASCADE,
    account_number TEXT UNIQUE NOT NULL,
    opened_date DATE DEFAULT CURRENT_DATE,
    status TEXT DEFAULT 'ACTIVE'
);
COMMENT ON TABLE myedw.customer_accounts IS 'Financial account for each customer used in transactions.';

-- =====================================================================
-- Customer Addresses
-- =====================================================================
CREATE TABLE myedw.customer_addresses (
    address_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL REFERENCES myedw.customer_profiles(customer_id) ON DELETE CASCADE,
    line1 TEXT NOT NULL,
    line2 TEXT,
    city TEXT NOT NULL,
    postal_code TEXT,
    country_code CHAR(2) REFERENCES myedw.reference_countries(country_code),
    is_primary BOOLEAN DEFAULT FALSE
);
COMMENT ON TABLE myedw.customer_addresses IS 'Customer physical or mailing addresses.';
COMMENT ON COLUMN myedw.customer_addresses.is_primary IS 'Flag to mark the default address for shipping/billing.';

-- ===============================================================
-- CREATE TABLE: customer_loyalty_points
-- ===============================================================
CREATE TABLE IF NOT EXISTS myedw.customer_loyalty_points (
    customer_id BIGINT PRIMARY KEY REFERENCES myedw.customer_profiles(customer_id),
    points_balance BIGINT NOT NULL DEFAULT 0
);

COMMENT ON TABLE myedw.customer_loyalty_points IS
'Stores loyalty or reward point balances per customer.';
COMMENT ON COLUMN myedw.customer_loyalty_points.points_balance IS
'Total available loyalty points.';

-- ===============================================================
-- CREATE TABLE: customer_preferences
-- ===============================================================
CREATE TABLE IF NOT EXISTS myedw.customer_preferences (
    pref_id BIGSERIAL PRIMARY KEY,
    customer_id BIGINT NOT NULL REFERENCES myedw.customer_profiles(customer_id),
    prefers_email BOOLEAN DEFAULT TRUE,
    prefers_sms BOOLEAN DEFAULT FALSE
);

COMMENT ON TABLE myedw.customer_preferences IS
'Stores communication channel preferences for each customer.';

COMMENT ON COLUMN myedw.customer_preferences.prefers_email IS
'If TRUE, customer prefers receiving updates via email.';
COMMENT ON COLUMN myedw.customer_preferences.prefers_sms IS
'If TRUE, customer prefers receiving updates via SMS.';

-- ===============================================================
-- MASTER SEGMENT TABLE
-- ===============================================================

CREATE TABLE IF NOT EXISTS myedw.customer_segments (
    segment_id BIGSERIAL PRIMARY KEY,
    segment_name TEXT NOT NULL UNIQUE,
    description TEXT
);


COMMENT ON TABLE myedw.customer_segments IS
'Defines customer segments such as VIP, At Risk, or New.';
COMMENT ON COLUMN myedw.customer_segments.segment_name IS
'Business label for segment classification.';

-- ===============================================================
-- SEGMENT BRIDGETABLE
-- ===============================================================
CREATE TABLE IF NOT EXISTS myedw.customer_segments_bridge (
    customer_id BIGINT NOT NULL REFERENCES myedw.customer_profiles(customer_id),
    segment_id  BIGINT NOT NULL REFERENCES myedw.customer_segments(segment_id),
    assigned_date DATE NOT NULL DEFAULT CURRENT_DATE,
    PRIMARY KEY (customer_id, segment_id)
);

COMMENT ON TABLE myedw.customer_segments_bridge IS
'Bridge table linking customers to one or more segment definitions.';

COMMENT ON COLUMN myedw.customer_segments_bridge.assigned_date IS
'Date when the customer was associated with the segment.';

ALTER TABLE myedw.customer_segments
ADD CONSTRAINT uq_customer_segments_name UNIQUE (segment_name);

-- =====================================================================
-- Products
-- =====================================================================
CREATE TABLE myedw.inventory_products (
    product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_code TEXT UNIQUE NOT NULL,
    product_name TEXT NOT NULL,
    category TEXT,
    unit_price NUMERIC(12,2) NOT NULL,
    cost_price NUMERIC(12,2),
    currency_code CHAR(3) REFERENCES myedw.reference_currencies(currency_code),
    is_active BOOLEAN DEFAULT TRUE
);
COMMENT ON TABLE myedw.inventory_products IS 'List of all sellable or stocked products.';



-- =====================================================================
-- Sales Orders
-- =====================================================================
CREATE TABLE myedw.sales_orders (
    order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL REFERENCES myedw.customer_profiles(customer_id),
    channel_id BIGINT REFERENCES myedw.reference_sales_channels(channel_id),
    order_date DATE DEFAULT CURRENT_DATE,
    status TEXT DEFAULT 'NEW',
    total_amount NUMERIC(14,2) DEFAULT 0,
    currency_code CHAR(3) REFERENCES myedw.reference_currencies(currency_code),
    payment_method_id BIGINT REFERENCES myedw.reference_payment_methods(payment_method_id)
);
COMMENT ON TABLE myedw.sales_orders IS 'Sales order header for each customer purchase.';

-- =====================================================================
-- Sales Order Items
-- =====================================================================
CREATE TABLE myedw.sales_order_items (
    order_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES myedw.sales_orders(order_id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES myedw.inventory_products(product_id),
    quantity INT NOT NULL DEFAULT 1,
    unit_price NUMERIC(12,2) NOT NULL,
    discount_amount NUMERIC(12,2) DEFAULT 0,
    line_total NUMERIC(14,2) GENERATED ALWAYS AS (quantity * (unit_price - discount_amount)) STORED
);
COMMENT ON TABLE myedw.sales_order_items IS 'Individual product lines per sales order.';
CREATE INDEX idx_sales_order_items_order_id ON myedw.sales_order_items(order_id);

-- =====================================================================
-- Sales Shipments
-- =====================================================================
CREATE TABLE myedw.sales_shipments (
    shipment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES myedw.sales_orders(order_id),
    shipped_date DATE,
    carrier TEXT,
    tracking_number TEXT,
    status TEXT DEFAULT 'PENDING'
);
COMMENT ON TABLE myedw.sales_shipments IS 'Shipment details for fulfilled sales orders.';

-- =====================================================================
-- Sales Invoices
-- =====================================================================
CREATE TABLE myedw.sales_invoices (
    invoice_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES myedw.sales_orders(order_id),
    invoice_date DATE DEFAULT CURRENT_DATE,
    due_date DATE,
    total_amount NUMERIC(14,2),
    tax_amount NUMERIC(12,2),
    paid_amount NUMERIC(14,2) DEFAULT 0,
    currency_code CHAR(3) REFERENCES myedw.reference_currencies(currency_code)
);
COMMENT ON TABLE myedw.sales_invoices IS 'Invoices issued for customer orders.';

-- =====================================================================
-- Sales Payments
-- =====================================================================
CREATE TABLE myedw.sales_payments (
    payment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id BIGINT REFERENCES myedw.sales_invoices(invoice_id),
    payment_date DATE DEFAULT CURRENT_DATE,
    amount NUMERIC(14,2),
    method_id BIGINT REFERENCES myedw.reference_payment_methods(payment_method_id),
    reference_no TEXT
);
COMMENT ON TABLE myedw.sales_payments IS 'Payments received against invoices.';

-- =====================================================================
-- Sales Returns
-- =====================================================================
CREATE TABLE myedw.sales_returns (
    return_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT REFERENCES myedw.sales_orders(order_id),
    return_date DATE DEFAULT CURRENT_DATE,
    reason TEXT,
    refund_amount NUMERIC(14,2)
);
COMMENT ON TABLE myedw.sales_returns IS 'Returned or refunded sales order information.';

-- =====================================================================
-- Analytics Fact Table: Daily Sales
-- =====================================================================
CREATE TABLE myedw.analytics_fact_sales_daily (
    date_id DATE REFERENCES myedw.reference_calendar(date_id),
    product_id BIGINT REFERENCES myedw.inventory_products(product_id),
    channel_id BIGINT REFERENCES myedw.reference_sales_channels(channel_id),
    order_count BIGINT DEFAULT 0,
    revenue_amount NUMERIC(14,2) DEFAULT 0,
    PRIMARY KEY (date_id, product_id, channel_id)
);
COMMENT ON TABLE myedw.analytics_fact_sales_daily IS 'Aggregated daily sales metrics for analytics.';

