-- =====================================================================
-- 01_MYEDW_SCHEMA - CHUNK 3: HR + FINANCE + SUPPORT + DOCUMENTS
-- Target: PostgreSQL 16.x
-- Schema: myedw
-- =====================================================================

SET search_path TO myedw, public;

-- =====================================================================
-- HR DOMAIN
-- =====================================================================
CREATE TABLE myedw.hr_departments (
    department_id BIGINT PRIMARY KEY,
    department_name TEXT NOT NULL
);

CREATE TABLE myedw.hr_job_titles (
    job_title_id BIGINT PRIMARY KEY,
    job_title_name TEXT NOT NULL
);

CREATE TABLE myedw.hr_employees (
    employee_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name TEXT NOT NULL,
    last_name  TEXT NOT NULL,
    email TEXT UNIQUE,
    phone TEXT,
    hire_date DATE DEFAULT CURRENT_DATE,
    department_id BIGINT REFERENCES myedw.reference_departments(department_id),
    job_title_id BIGINT REFERENCES myedw.reference_job_titles(job_title_id),
    status_code TEXT REFERENCES myedw.reference_employee_status(status_code),
    salary NUMERIC(14,2),
    country_code CHAR(2) REFERENCES myedw.reference_countries(country_code)
);
COMMENT ON TABLE myedw.hr_employees IS 'Master employee table with department and job associations.';

CREATE INDEX idx_hr_employees_department_id ON myedw.hr_employees(department_id);

CREATE TABLE myedw.hr_payroll (
    payroll_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES myedw.hr_employees(employee_id) ON DELETE CASCADE,
    pay_period_start DATE,
    pay_period_end DATE,
    gross_pay NUMERIC(14,2),
    tax_withheld NUMERIC(14,2),
    net_pay NUMERIC(14,2)
);
COMMENT ON TABLE myedw.hr_payroll IS 'Employee payroll transactions per pay period.';

CREATE TABLE myedw.hr_performance_reviews (
    review_id BIGINT PRIMARY KEY,
    employee_id BIGINT REFERENCES myedw.hr_employees(employee_id),
    review_year INT NOT NULL,
    rating NUMERIC(2,1),
    reviewer_id BIGINT REFERENCES myedw.hr_employees(employee_id),
    comments TEXT);

COMMENT ON TABLE myedw.hr_performance_reviews IS 'Employee performance review history.';

-- =====================================================================
-- FINANCE DOMAIN
-- =====================================================================

CREATE TABLE myedw.finance_accounts (
    account_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_code TEXT UNIQUE NOT NULL,
    account_name TEXT NOT NULL,
    account_type TEXT CHECK (account_type IN ('ASSET','LIABILITY','EXPENSE','REVENUE','EQUITY')),
    parent_account_id BIGINT REFERENCES myedw.finance_accounts(account_id)
);
COMMENT ON TABLE myedw.finance_accounts IS 'Chart of accounts hierarchy for general ledger.';

CREATE TABLE myedw.finance_journal_entries (
    journal_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_date DATE DEFAULT CURRENT_DATE,
    description TEXT,
    created_by BIGINT REFERENCES myedw.hr_employees(employee_id)
);
COMMENT ON TABLE myedw.finance_journal_entries IS 'Journal entry header information.';

CREATE TABLE myedw.finance_journal_lines (
    line_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    journal_id BIGINT REFERENCES myedw.finance_journal_entries(journal_id) ON DELETE CASCADE,
    account_id BIGINT REFERENCES myedw.finance_accounts(account_id),
    debit_amount NUMERIC(14,2) DEFAULT 0,
    credit_amount NUMERIC(14,2) DEFAULT 0
);
COMMENT ON TABLE myedw.finance_journal_lines IS 'Debit/credit lines belonging to journal entries.';

CREATE TABLE myedw.finance_ap_vendors (
    vendor_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendor_code TEXT UNIQUE NOT NULL,
    vendor_name TEXT NOT NULL,
    country_code CHAR(2) REFERENCES myedw.reference_countries(country_code)
);
COMMENT ON TABLE myedw.finance_ap_vendors IS 'Accounts Payable vendors and suppliers.';

CREATE TABLE myedw.finance_ap_bills (
    bill_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendor_id BIGINT REFERENCES myedw.finance_ap_vendors(vendor_id),
    bill_date DATE DEFAULT CURRENT_DATE,
    due_date DATE,
    currency_code CHAR(3) REFERENCES myedw.reference_currencies(currency_code),
    status TEXT DEFAULT 'OPEN'
);
COMMENT ON TABLE myedw.finance_ap_bills IS 'AP bills received from vendors.';

CREATE TABLE myedw.finance_ap_bill_lines (
    bill_line_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bill_id BIGINT REFERENCES myedw.finance_ap_bills(bill_id) ON DELETE CASCADE,
    account_id BIGINT REFERENCES myedw.finance_accounts(account_id),
    line_amount NUMERIC(14,2),
    description TEXT
);
COMMENT ON TABLE myedw.finance_ap_bill_lines IS 'Line-item detail for AP bills.';

-- =====================================================================
-- SUPPORT DOMAIN
-- =====================================================================

CREATE TABLE myedw.support_agents (
    agent_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT REFERENCES myedw.hr_employees(employee_id),
    hire_date DATE DEFAULT CURRENT_DATE,
    is_active BOOLEAN DEFAULT TRUE
);
COMMENT ON TABLE myedw.support_agents IS 'Support agents linked to HR employees.';

CREATE TABLE myedw.support_ticket_categories (
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name TEXT UNIQUE NOT NULL,
    description TEXT
);
COMMENT ON TABLE myedw.support_ticket_categories IS 'Issue categories for customer support tickets.';

CREATE TABLE myedw.support_tickets (
    ticket_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT REFERENCES myedw.customer_profiles(customer_id),
    category_id BIGINT REFERENCES myedw.support_ticket_categories(category_id),
    agent_id BIGINT REFERENCES myedw.support_agents(agent_id),
    opened_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    closed_at TIMESTAMP,
    status TEXT DEFAULT 'OPEN',
    subject TEXT,
    description TEXT
);
COMMENT ON TABLE myedw.support_tickets IS 'Customer support cases handled by agents.';

CREATE TABLE myedw.support_ticket_comments (
    comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id BIGINT REFERENCES myedw.support_tickets(ticket_id) ON DELETE CASCADE,
    agent_id BIGINT REFERENCES myedw.support_agents(agent_id),
    comment_text TEXT,
    commented_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE myedw.support_ticket_comments IS 'Conversation log for each ticket.';

-- =====================================================================
-- DOCUMENT MANAGEMENT DOMAIN
-- =====================================================================

CREATE TABLE myedw.doc_repositories (
    repo_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    repo_name TEXT UNIQUE NOT NULL,
    repo_type TEXT CHECK (repo_type IN ('HR','FINANCE','SUPPORT','MARKETING')),
    base_url TEXT,
    description TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE myedw.doc_repositories IS 'Logical document repositories per department.';

CREATE TABLE myedw.doc_collections (
    collection_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    repo_id BIGINT REFERENCES myedw.doc_repositories(repo_id),
    department TEXT,
    collection_key TEXT,
    path_prefix TEXT,
    is_active BOOLEAN DEFAULT TRUE
);
COMMENT ON TABLE myedw.doc_collections IS 'Sub-folders or categorized document collections.';

CREATE TABLE myedw.doc_documents (
    doc_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collection_id BIGINT REFERENCES myedw.doc_collections(collection_id),
    doc_type TEXT REFERENCES myedw.reference_document_types(doc_type),
    title TEXT,
    mime_type TEXT,
    storage_url TEXT,
    sha256_hex TEXT,
    size_bytes BIGINT,
    language TEXT,
    received_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status TEXT DEFAULT 'ACTIVE'
);
COMMENT ON TABLE myedw.doc_documents IS 'Document master table storing metadata and storage paths.';

CREATE TABLE myedw.doc_document_versions (
    version_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_id BIGINT REFERENCES myedw.doc_documents(doc_id) ON DELETE CASCADE,
    version_no INT,
    uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    storage_url TEXT,
    sha256_hex TEXT,
    size_bytes BIGINT,
    notes TEXT
);
COMMENT ON TABLE myedw.doc_document_versions IS 'Version history of stored documents.';

CREATE TABLE myedw.doc_acl (
    acl_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_id BIGINT REFERENCES myedw.doc_documents(doc_id) ON DELETE CASCADE,
    principal_type TEXT CHECK (principal_type IN ('USER','ROLE','DEPARTMENT')),
    principal_key TEXT,
    permission TEXT CHECK (permission IN ('READ','WRITE','ADMIN')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE myedw.doc_acl IS 'Access-control entries defining who can access each document.';

